import productImage1 from './assets/images/products/florianopolis.webp'
import productImage2 from './assets/images/products/ushuaia.webp'
import productImage3 from './assets/images/products/egipto.webp'
import productImage4 from './assets/images/products/paris.webp'
import productImage5 from './assets/images/products/dubai.webp'
import productImage6 from './assets/images/products/turquia.webp'
import productImage7 from './assets/images/products/cataratas.webp'
import productImage8 from './assets/images/products/nashville.webp'
import productImage9 from './assets/images/products/zanzibar.webp'
import productImage10 from './assets/images/products/españa.webp'
import productImage11 from './assets/images/products/humahuaca.webp'
import productImage12 from './assets/images/products/uganda.webp'

const productos = [
    {id: 'florianopolis', nombre: 'Florianopolis', precio: 449, categoria: 'america-del-sur', imagen: productImage1, disponibilidad: 43, fecha: '30/01/2023',  regimen: 'Media pensón', hotel: 'Hotel Porto Sol Quality', descripcion: 'Encanto en las Costas de Florianópolis: Aventura y Relax en Brasil', itinerario: 'Día 1: Salida desde Montevideo en horas de la mañana hacia Florianópolis. Desayuno y cena a bordo. Día 2: Desayuno a bordo, llegada a Florianópolis y traslado al Hotel Porto Sol Quality en Canasvieiras. Después de registrarte en el hotel, relájate en la playa de Canasvieiras y disfruta del almuerzo en el restaurante del hotel. Por la noche, tienes la opción de cenar y disfrutar de un espectáculo en el restaurante Mystic Dinner Show. Este espectáculo ofrece una experiencia cultural y artística única con danzas y música en vivo. Día 3: Después del desayuno en el hotel, pasa el día en Canasvieiras o dirígete a Beto Carrero World para disfrutar de emocionantes atracciones y espectáculos (opcional). Cena en el restaurante del hotel. Día 4: Después del desayuno, día libre para disfrutar de la playa y explorar Canasvieiras. Cena en el restaurante del hotel. Día 5: Después del desayuno, día libre o tienes la opción de realizar una excursión en el "Barco Pirata", una experiencia única en un barco temático (opcional). Cena en el restaurante del hotel. Día 6: Realiza el check-out en el Hotel Porto Sol Quality y emprende el regreso a Montevideo en bus. Las comidas serán a bordo. Día 7: Llegada a Montevideo y fin de nuestros servicios.', opcionalUno: 'Cena Mystic Dinner Show', preciOpcionalUno: 50, opcionalDos: 'Beto Carrero World', preciOpcionalDos: 60, opcionalTres: 'Barco Pirata', preciOpcionalTres: 25, disponibilidadOpcionales: 43},
    
    {id: 'zanzibar', nombre: 'Zanzíbar', precio: 3999, categoria: 'africa', imagen: productImage9, disponibilidad: 16, fecha: '20/02/2023', regimen: 'Sólo desayuno', hotel: 'Gaylord Opryland Resort', descripcion: 'Zanzíbar: Islas, Cultura y Aventuras', itinerario: 'Día 1: En el primer día de tu viaje, llegarás al Aeropuerto Internacional de Zanzíbar. Después de aterrizar, te trasladarás a tu hotel y realizarás el proceso de registro. Día 2:  El segundo día se dedica a explorar Stone Town, el pintoresco casco antiguo de Zanzíbar. Visitarás lugares emblemáticos como el Mercado de las Especias y el Palacio de Beit-el-Sahel. Visita al Museo Casa de Freddie Mercury (opcional). Día 3:  En este día, relájate en una de las hermosas playas de Zanzíbar, como Nungwi y Kendwa Beach. Puedes disfrutar de actividades como nadar y hacer snorkel en las aguas cristalinas. Después de un almuerzo en un restaurante de playa, el tiempo es tuyo para disfrutar de las actividades playeras o explorar la zona a tu propio ritmo. Día 4:  Día libre o puedes hacer el Safari Azul. Esta aventura en barco te llevará a explorar los impresionantes arrecifes de coral y la vida marina de Zanzíbar. Tendrás la oportunidad de hacer snorkel y avistar delfines (opcional)Día 5:  Este día comienza con una visita a la Selva de Jozani, el único parque nacional de Zanzíbar, donde podrás observar a los encantadores monos colobos rojos. Tarde libre. Día 6:  En tu último día en Zanzíbar, disfrutarás de un día libre para explorar la isla a tu ritmo. Puedes visitar mercados locales, descubrir lugares de interés adicionales o simplemente relajarte en la playa. Además, tienes la opción de elegir una actividad adicional, como un paseo en dhow tradicional (opcional). La jornada culmina con una cena de despedida y un traslado al aeropuerto para tomar tu vuelo de regreso.', opcionalUno: 'Museo Freddie Mercury', preciOpcionalUno: 15, opcionalDos: 'Safari Azul', preciOpcionalDos: 55, opcionalTres: 'Paseo en dhow', preciOpcionalTres: 40, disponibilidadOpcionales: 20},
    
    {id: 'egipto', nombre: 'Egipto', precio: 3799, categoria: 'africa', imagen: productImage3, disponibilidad: 9, fecha: '25/08/2023', regimen: 'Sólo desayuno', hotel: 'Movenpick Hotel Cairo Pyramids,  Steigenberger Nile Palace Luxor, Sofitel Legend Old Cataract Aswan', descripcion: 'Maravillas de Egipto: 15 Días de Aventura en el País de los Faraones', itinerario: 'Día 1: Salida desde Montevideo hacia El Cairo en avión. Día 2-4: El Cairo: Llegada al Aeropuerto Internacional de El Cairo. Traslado al hotel y tiempo libre para descansar y aclimatarse. Durante los siguientes días, exploración de El Cairo con visitas a las Pirámides de Giza, la Esfinge, el Museo Egipcio y el Mercado Khan el Khalili. Día 5: Traslado a Luxor en avión. Llegada y visita al Templo de Karnak. Día 6-7: Luxor: Exploración de la Orilla Este con visitas al Valle de los Reyes, el Templo de Hatshepsut y los Colosos de Memnón. En la Orilla Oeste, visita al Templo de Luxor. Día 8: Traslado a Asuán por tierra o en un crucero por el Nilo (opcional). Llegada y visita al Templo de Filae. Día 9-10: Asuán: Excursión a la Alta Presa de Asuán y el Templo de Abu Simbel (opcional). Navegación en faluca por el Nilo y visita a una aldea nubia. Día 11: Regreso a El Cairo en avión. Día 12-13: El Cairo: Días libres para explorar más de la ciudad, con opciones como una visita a la Ciudadela de Saladino, la Mezquita de Alabastro y el Barrio Copto. También tendrás tiempo para compras en el Gran Bazar. Día 14: Excursión a Alejandría desde El Cairo (opcional). Día 15: Regreso a Montevideo desde El Cairo en avión.', opcionalUno: 'Templo de Abu Simbel', preciOpcionalUno: 35, opcionalDos: 'Crucero por el Nilo', preciOpcionalDos: 250, opcionalTres: 'Excursión a Alejandría', preciOpcionalTres: 100, disponibilidadOpcionales: 9},
    
    {id: 'parís', nombre: 'París', precio: 2699, categoria: 'europa', imagen: productImage4, disponibilidad: 13, fecha: '18/03/2023', regimen: 'Sólo desayuno', hotel: 'Hotel Le Meurice', descripcion: 'París en Cinco Días: Arte, Historia y Aventuras', itinerario: 'Día 1: Llegada a París con traslado al Aeropuerto de París-Charles de Gaulle, check-in en el hotel, seguido de un relajante paseo por los Campos Elíseos con vistas al Arco de Triunfo. Día 2: Exploración de París con una mañana en el Museo del Louvre para contemplar obras maestras como la Mona Lisa, almuerzo en un café parisino, seguido de una tarde en el Jardín de las Tullerías y visita al Museo de Orsay, concluyendo con una cena en un restaurante con vista a la Torre Eiffel (opcional). Día 3: Día libre o puedes contratar la excursión a Palacio de Versalles y sus jardines, explorando los majestuosos salones y la Galería de los Espejos (opcional). Día 4: Otro día libre con la posibilidad de una excursión a Mont Saint-Michel, una impresionante abadía en una isla rocosa, explorando la abadía, las calles empedradas y las vistas panorámicas (opcional). Día 5: Opción de una excursión a las Catacumbas de París, un laberinto subterráneo con huesos humanos, experimentando su historia única y escalofriante. Luego, checkout del hotel y vuelo de regreso a casa desde el Aeropuerto de París-Charles de Gaulle.', opcionalUno: 'Cena vista Torre Eiffel ', preciOpcionalUno: 125, opcionalDos: 'Palacio de Versalles', preciOpcionalDos: 50, opcionalTres: 'Mont Saint-Michel', preciOpcionalTres: 180, disponibilidadOpcionales: 9},
    
    {id: 'dubái', nombre: 'Dubái', precio: 4999, categoria: 'asia', imagen: productImage5, disponibilidad: 21, fecha: '02/09/2023', regimen: 'Sólo desayuno', hotel: 'Ramada by Wyndham Downtown', descripcion: 'Descubriendo Dubai: Una Semana en el Corazón de los Emiratos Árabes Unidos', itinerario: 'Durante tu viaje de 7 días a Dubái, comenzarás cada día con un desayuno en tu hotel. El Día 1, llegarás al Aeropuerto Internacional de Dubái y harás el check-in en tu hotel. Tendrás tiempo libre para relajarte en la playa o la piscina. El Día 2, explorarás la ciudad visitando el Burj Khalifa, el Dubai Mall y el Dubai Fountain Show. podrás disfrutar de una cena en At.mosphere, el restaurante del Burj Khalifa con vistas espectaculares (opcional). El Día 3, disfrutarás de un emocionante safari en el desierto con 4x4, paseos en camello y sandboarding. Terminarás con una cena buffet bajo las estrellas en el campamento del desierto. El Día 4 lo dedicarás a explorar Abu Dabi, la capital de los Emiratos Árabes Unidos, con visitas a sus lugares emblemáticos como la Gran Mezquita Sheikh Zayed, el Palacio Presidencial y el Museo del Louvre en Abu Dabi. El Día 5, tendrás tiempo libre o podrás optar por un emocionante viaje en hidroavión sobre Dubái. Ofrece vistas panorámicas de famosos puntos de referencia como Palm Jumeirah y el Burj Al Arab (opcional). El Día 6, disfrutarás de tiempo libre o podrás explorar la Marina de Dubái en un yate privado (opcional). Finalmente, el Día 7, harás el check-out del hotel y te dirigirás al aeropuerto para tu vuelo de regreso a Uruguay.' , opcionalUno: 'Sobrevuelo en Hidroavión', preciOpcionalUno: 175, opcionalDos: 'Recorrido Yate Privado', preciOpcionalDos: 250, opcionalTres: 'Cena At.mosphere', preciOpcionalTres: 200, disponibilidadOpcionales: 13 },
    
    {id: 'turquía', nombre: 'Turquía', precio: 4399, categoria: 'asia', imagen: productImage6, disponibilidad: 27, fecha: '07/02/2023', regimen: 'Media pensón', hotel: 'Sultanahmet Palace Hotel, Radisson Blu Hotel, Cappadocia Cave Suites, The Marmara Antalya', descripcion: 'Turquía Mágica: Una Experiencia Inolvidable', itinerario: 'Día 1: Llegada a Estambul, traslado al hotel y cena incluida. Día 2: Desayuno en el hotel, visita a la Mezquita Azul, Santa Sofía y el Palacio Topkapi en Estambul. Tiempo libre para almorzar antes de la cena en el hotel. Día 3: Desayuno, visita al Gran Bazar de Estambul para hacer compras y almorzar. Cena en el hotel. Día 4: Después del desayuno, viaje a Ankara en. Visita al Museo de las Civilizaciones de Anatolia y el Mausoleo de Atatürk. Cena en el hotel. Día 5: Continuación del viaje de Ankara a Capadocia. Día 6: Desayuno en el hotel, paseo en Globo aerostático (opcional) y exploración de Capadocia. Visita al Valle de los Monjes, Museo al Aire Libre de Göreme y ciudades subterráneas (opcional). Cena en el hotel Día 7: Desayuno en el hotel, continuación de la exploración de Capadocia, día libre y cena en el hotel. Día 8: Desayuno en el hotel, viaje a Antalya en automóvi, check-in en el hotel con cena incluida. Día 9: Exploración de Antalya, incluyendo la Ciudad Vieja, el Museo de Antalya y tiempo en la playa. Almuerzo en restaurante local. Día 10: Desayuno en el hotel y día libre en Antalya para explorar o relajarse en la playa. Día 11: Desayuno en el hotel, vuelo de regreso a Estambul, check-in en el hotel con cena incluida, tendrás la opción de embarcarte en un emocionante crucero por el estrecho del Bósforo, donde disfrutarás de una cena inolvidable (opcional). Día 12: Desayuno en el hotel y traslado al aeropuerto internacional de Estambul para el vuelo de regreso a casa.', opcionalUno: 'Globo aerostático', preciOpcionalUno: 300, opcionalDos: 'Ciudades subterráneas', preciOpcionalDos: 50, opcionalTres: 'Crucero por el Bósforo', preciOpcionalTres: 120, disponibilidadOpcionales: 36},
    
    {id: 'cataratas', nombre: 'Cataratas', precio: 499, categoria: 'america-del-sur', imagen: productImage7, disponibilidad: 49, fecha: '08/05/2023', regimen: 'Media pensón', hotel: 'Hotel Carima', descripcion: 'Cataratas del Iguazú: Entre las Aguas y la Selva', itinerario: 'Día 01: Salida en bus Semi cama con cena y desayuno abordo, guía acompañante. Día 02: Llegada. Alojamiento. Resto del día libre para disfrutar del hotel y o paseos. Cena.Día 03: Desayuno. Salida en horas de la mañana para visitar Cataratas Brasileñas. Ingreso al Parque Nacional y llegada hasta el Punto Panorámico, frente al hotel Das Cataratas y desde allí dar comienzo a una caminata por pasarelas observando gran parte de los 275 saltos de agua y viendo el gran espectáculo que nos ofrece esta maravilla de la naturaleza. Posibilidad de realizar el Safari Macuco (opcional) donde nos internaremos en vehículos especiales en zona interna del parque y posteriormente en gomones realizar el trayecto por el río hasta enfrentarnos con los saltos en un espectáculo realmente indescriptible. Tiempo libre también para realizar la visita al Parque de las Aves(opcional). Cena. Día 04: Salida en horas de la mañana cruzando el Puente Internacional de la Amistad a territorio paraguayo y visitar la Represa de Itaipú. De regreso visita de Ciudad del Este donde dispondremos de tiempo para compras. Regreso al hotel en la tarde. Cena. Día 05: Salida en la mañana cruzando el Puente Tancredo Neves a territorio argentino e ingresar al Parque Nacional para visitar las Cataratas Argentinas. Recorrido por los senderos superior, inferior y Garganta del Diablo. Cena. Día 06: Partida con equipajes en horas de la mañana hacia territorio argentino. Visita de las Ruinas Jesuíticas de San Ignacio Mini con ingreso incluido y la Casa del Escritor uruguayo Horacio Quiroga (opcional) Almuerzo. Día 07: Llegada en horas de la mañana. Fin de nuestros servicios', opcionalUno: 'Safari Macuco', preciOpcionalUno: 70, opcionalDos: 'Parque de las Aves', preciOpcionalDos: 20, opcionalTres: 'Casa Horacio Quiroga', preciOpcionalTres: 10, disponibilidadOpcionales: 81},
    
    {id: 'nashville', nombre: 'Nashville', precio: 3399, categoria: 'america-del-norte', imagen: productImage8, disponibilidad: 15, fecha: '31/10/2023', regimen: 'Sólo desayuno', hotel: 'Gaylord Opryland Resort', descripcion: 'Explora Nashville y Huntsville', itinerario: 'Día 1:  En tu primer día, llegarás a Nashville y te registras en tu hotel. Resto del día libre. Día 2: Día libre, te recomendamos hacer el tour en Huntsville, Alabama. Allí, tendrás la oportunidad de explorar el Centro Espacial de Huntsville, donde encontrarás emocionantes exhibiciones relacionadas con la exploración espacial y la NASA (opcional). Día 3:  Este día está reservado para sumergirte en la cultura musical de Nashville. Comienza con una visita al Museo Country Music Hall of Fame, donde descubrirás la rica historia de la música country. Considera un tour por los estudios de grabación RCA Studio B para conocer más sobre la historia de la música country y ver dónde grabaron leyendas como Elvis Presley (opcional). Día 4:  Comienza el día con una visita al Museo y Parthenon de Nashville, ubicado en el Parque Centenario, donde te maravillarás con una réplica a escala real del Partenón griego. Por la tarde, sumérgete en la belleza natural y el arte al aire libre en el Jardín Botánico de Cheekwood. Día 5: En tu último día en Nashville, empieza con un desayuno en el hotel y realiza el check-out. A cntinuación, visita la Plantación Andrew Jacksons Hermitage para explorar la historia presidencial y la vida en una antigua plantación  (opcional). Después de un almuerzo en un restaurante cercano, si el tiempo lo permite, puedes dar un relajante paseo por el Parque Percy Warner para disfrutar de la naturaleza antes de partir al aeropuerto.', opcionalUno: 'Marshall SpaceCenter', preciOpcionalUno: 150, opcionalDos: 'RCA Studio B', preciOpcionalDos: 45, opcionalTres: 'Plantación Hermitage', preciOpcionalTres: 60, disponibilidadOpcionales: 25},
    
    {id: 'ushuaia', nombre: 'Ushuaia', precio: 1799, categoria: 'america-del-sur', imagen: productImage2, disponibilidad: 17, fecha: '03/04/2023', regimen: 'Sólo desayuno', hotel: 'Hotel Mustapic', descripcion: 'Descubriendo la Maravilla Austral: Aventura en Ushuaia', itinerario: 'Día 1: Comienzas tu viaje desde Montevideo con una escala en Buenos Aires antes de llegar a Ushuaia, donde te trasladarás al hotel y dispondrás de tiempo libre para aclimatarte. Día 2: Exploras el impresionante Parque Nacional Tierra del Fuego, disfrutando de caminatas, paisajes asombrosos y un viaje en el Tren del Fin del Mundo. Por la tarde, visitas el Museo Marítimo y del Presidio de Ushuaia. Día 3: Día libre, tienes la opción de explorar Ushuaia a tu ritmo o realizar una emocionante excursión al Glaciar Vinciguerra, con caminatas entre montañas y bosques, y la posibilidad de caminar sobre el glaciar (opcional). Día 4: La aventura continúa con una emocionante navegación por el Canal Beagle, donde avistarás aves marinas, lobos marinos y el Faro Les Eclaireurs. Día 5: Tendrás tiempo para explorar la ciudad o elegir una emocionante actividad opcional que incluye un paseo en 4x4, una excursión en kayak y una visita a una estancia patagónica (opcional). Día 6: Te aventuras al majestuoso Glaciar Martial, con caminatas en la nieve y vistas panorámicas espectaculares. Día 7: Día libre, o puedes optar por realizar un trekking de dificultad media a la Laguna Esmeralda (opcional). Día 8: Disfrutas de una última mañana en Ushuaia antes de emprender el viaje de regreso a Montevideo, primero a Buenos Aires y luego a Montevideo. Día 9: Llegada a Montevideo, finalizando el viaje.', opcionalUno: 'Trekking Glaciar Vinciguerra', preciOpcionalUno: 80, opcionalDos: 'Trekking Laguna Esmeralda', preciOpcionalDos: 70, opcionalTres: 'Paseo en 4x4 y kayak', preciOpcionalTres: 40, disponibilidadOpcionales: 10},

    {id: 'madrid', nombre: 'Madrid', precio: 2899, categoria: 'europa', imagen: productImage10, disponibilidad: 17, fecha: '23/06/2023', regimen: 'Sólo desayuno', hotel: 'Hotel Madrid', descripcion: 'Descubre la capital de España: Experiencia en Madrid', itinerario: 'Durante este emocionante viaje a Madrid, en el Día 1 llegarás a la ciudad y te trasladarás al Hotel Madrid, donde tendrás tiempo libre para relajarte y aclimatarte. En el Día 2, explorarás las joyas artísticas de Madrid con una visita al Museo del Prado y disfrutarás de la belleza natural en el Parque del Retiro. El Día 3 te llevará a descubrir la historia real de Madrid con una emocionante excursión al majestuoso Palacio Real y la impresionante Catedral de la Almudena. Si lo deseas, el Día 4 puedes sumergirte en el mundo del arte contemporáneo con una visita al Museo Reina Sofía (Opcional). El Día 5 sentirás la pasión por el fútbol con una visita al Estadio Santiago Bernabéu y un emocionante tour por las instalaciones del Real Madrid (Entrada no incluída). El Día 6 te llevará a la ciudad medieval de Toledo, con su arquitectura impresionante y su rico legado cultural. En el Día 7 tendrás tiempo libre para explorar la ciudad a tu propio ritmo, hacer compras o descubrir tus propios tesoros ocultos u optar por ir a descubrir Segovia y su imponente acueducto (Opcional). El Día 8 explorarás la historia de España con una emocionante excursión al Monasterio y Palacio Real de El Escorial. Finalmente, en el Día 9, te despedirás de Madrid y regresarás a casa con recuerdos inolvidables en el corazón.', opcionalUno: 'Museo Reina Sofía', preciOpcionalUno: 30, opcionalDos: 'Estadio Santiago Bernabéu', preciOpcionalDos: 50, opcionalTres: 'Excursión a Segovia', preciOpcionalTres: 80, disponibilidadOpcionales: 26},

    {id: 'salta', nombre: 'Salta', precio: 999, categoria: 'america-del-sur', imagen: productImage11, disponibilidad: 48, fecha: '13/07/2023', regimen: 'Media pensón', hotel: 'Hotel Altos de la Viña, Hotel Alejandro I', descripcion: 'Descubre la belleza del norte argentino', itinerario: 'Día 1: Llegada a Jujuy y traslado al Hotel Altos de la Viñay. Tiempo libre para aclimatarte. Día 2: Explora la ciudad de San Salvador de Jujuy, visitando la Plaza Belgrano y el Cabildo. Día 3: Día libre o excursión a las impresionantes Salinas Grandes (opcional), un vasto salar en las montañas. Día 4: Visita a la Quebrada de Humahuaca, declarada Patrimonio de la Humanidad por la UNESCO, con paradas en Purmamarca y Tilcara. Día 5: Viaje a Salta y exploración de la ciudad, incluyendo la Catedral y el Museo de Arqueología de Alta Montaña (MAAM). Día 6: Traslado a Cafayate, famosa por sus bodegas y paisajes espectaculares. Día 7: Día libre o Excursión a Cachi (opcional). Día 8: Día libre para explorar la ciudad de salta a tu ritmo. Día 9: Día para recorrer San Antonio de los Cobres y embarque en el emocionante Tren a las Nubes (opcional), un viaje ferroviario a través de las altas montañas. Día 10: Despedida del norte argentino y regreso a casa con recuerdos inolvidables.', opcionalUno: 'Salinas Grandes', preciOpcionalUno: 80, opcionalDos: 'Excursión a Cachi', preciOpcionalDos: 60, opcionalTres: 'Tren a las Nubes', preciOpcionalTres: 120, disponibilidadOpcionales: 78},

    {id: 'uganda',  nombre: 'Uganda', precio: 2699, categoria: 'africa', imagen: productImage12, disponibilidad: 24, fecha: '25/12/2023', regimen: 'Pensión completa', hotel: 'Hotel Serengeti', descripcion: 'Uganda: Aventura en el Corazón de África', itinerario: 'Día 1: Llegada a Entebbe y traslado al Hotel Serengeti. Tiempo libre para aclimatarte. Día 2: Safari de día completo en el Parque Nacional de Queen Elizabeth, donde podrás avistar leones, elefantes, búfalos y más. Día 3: Excursión al Bosque Impenetrable de Bwindi, hogar de los gorilas de montaña. Trekking para ver a estos majestuosos primates (opcional). Día 4: Salida hacia Jinja y emocionante día de rafting en el río Nilo (opcional) o Visita al Santuario de Chimpancés en Ngamba Island de lo contrario día libre para recorrer la capital Kampala. Día 5: Partida del hotel hacia aeropuerto internacional de Entebbe', opcionalUno: 'Trekking Gorilas Bwindi', preciOpcionalUno: 200, opcionalDos: 'Rafting Río Nilo', preciOpcionalDos: 80, opcionalTres: 'Santuario de Chimpancés', preciOpcionalTres: 100, disponibilidadOpcionales: 36}
]

export const getProductos = () => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(productos)
        }, 500)
    })
}

export const getProductByCategory = (categoryId) => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(productos.filter(prod => prod.categoria === categoryId))
        }, 500)
    })
}

export const getProductById = (productosId) => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(productos.find(prod => prod.id === productosId))
        }, 500)
    })
}